### ISSUE TITLE
Tokio module 'runtime' is private

### ISSUE THREAD

**Issue by ShayBox** [slowtec/tokio-modbus#191]
![image](https://github.com/slowtec/tokio-modbus/assets/9505196/6f0f0db3-3df4-49f6-8977-5e29816ddd7d)

**Comment by ShayBox** [comment]
This appears to be caused by this https://github.com/tokio-rs/tokio/blame/master/tokio/src/lib.rs#L536-L541

**Comment by flosse** [comment]
... so it's not related to `tokio-modbus`, right?

**Comment by ShayBox** [comment]
This is related to `tokio-modbus`, the error comes from it trying to access the `runtime` tokio module without the `cfg_rt!` (I don't know what that macro expands to, likely a cfg feature flag?)

**Comment by flosse** [comment]
hm... I tried to compile some examples and could not reproduce this error. Could you provide some more info to reproduce it?

**Comment by ShayBox** [comment]
`Cargo.toml`
```toml
[package]
name = "test"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-modbus = { version = "0.8.0", default-features = false, features = ["rtu-sync"] }
tokio-serial = "5.4.4"
```

`src/main.rs` [examples/rtu-client-sync.rs](https://github.com/slowtec/tokio-modbus/blob/main/examples/rtu-client-sync.rs)
```rust
// SPDX-FileCopyrightText: Copyright (c) 2017-2023 slowtec GmbH <post@slowtec.de>
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Synchronous RTU client example

fn main() -> Result<(), Box<dyn std::error::Error>> {
    use tokio_modbus::prelude::*;

    let tty_path = "/dev/ttyUSB0";
    let slave = Slave(0x17);

    let builder = tokio_serial::new(tty_path, 19200);

    let mut ctx = sync::rtu::connect_slave(&builder, slave)?;
    println!("Reading a sensor value");
    let rsp = ctx.read_holding_registers(0x082B, 2)?;
    println!("Sensor value is: {rsp:?}");

    Ok(())
}
```
