### ISSUE TITLE
Making a new release?

### ISSUE THREAD

**Issue by OrangeTux** [slowtec/tokio-modbus#43]
Thanks for your work on this project! 

The last release of this projects is `v0.3.5` which was released December 2019. Since than quite some changes have been made. Are you planning on releasing those soon?

**Comment by flosse** [comment]
> Are you planning on releasing those soon?

Absolutely! I think we'll make it happen within the next few weeks.
You can already test or use it by adding 

```toml
[patch.crates-io]
tokio-modbus = { git = "https://github.com/slowtec/tokio-modbus" }
```
to your `Cargo.toml`.
