### ISSUE TITLE
method not found in `impl futures::future::Future`

### ISSUE THREAD

**Issue by hanusek** [slowtec/tokio-modbus#52]
Cargo.toml :
```
[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
derive-new = "*"
tokio-modbus = "*"
tokio-serial = "*"
```

My Custom Example:
```
use tokio_modbus::prelude::*;
use tokio_serial::{Serial, SerialPortSettings};
use tokio_core::reactor::Core;
use futures::future::Future;

let mut settings = tokio_serial::SerialPortSettings::default();
settings.baud_rate = 115200;
settings.timeout = time::Duration::from_millis(500);
println!("settings is '{:?}'", settings);

let mut core = Core::new().unwrap();
let handle = core.handle();
let tty_path = "/dev/ttyUSB0";
const SLAVE_1: Slave = Slave(0x01);
	
let port = Serial::from_path_with_handle(tty_path, &settings, &handle.new_tokio_handle()).unwrap();
	
let task = rtu::connect_slave(&handle, port, slave).and_then(|ctx| {
	println!("Reading a sensor value");
	ctx
		.read_holding_registers(0x082B, 2)
		.and_then(move |rsp| {
			println!("Sensor value is: {:?}", rsp);
			Ok(())
			})
	});
	
core.run(task).unwrap();
```
Error:
```
method named `and_then` found for opaque type `impl futures::future::Future` in the current scope
let task = rtu::connect_slave(&handle, port, slave).and_then(|ctx| {
    |                                                             ^^^^^^^^ method not found in `impl futures::future::Future`
```

**Comment by flosse** [comment]
Your code has several mistakes. First you need to define the dependencies properly:

```toml
[dependencies]
derive-new = "*"
futures = "0.1"
serde = "*"
serde_json = "*"
serde_derive = "*"
tokio-modbus = { version = "0.3", default-features = false,  features =  ["rtu"] }
tokio-core = "0.1"
tokio-serial = "3"
 ```
And in your main code needs to be fixed this way:

```diff
+use std::time;
```

```diff
-    let task = rtu::connect_slave(&handle, port, slave).and_then(|ctx| {
+    let task = rtu::connect_slave(&handle, port, SLAVE_1).and_then(|ctx| {
```
